### ISSUE TITLE
How to emulate DP clock counter

### ISSUE THREAD

**Issue by olivieryuyu** [PeterLemon/N64#10]
Hello

I have  a N64 graphic command using DP clock counter (MFC0 V0, DP clock counter)

How to emulate this properly? We would need to fetch a clock counter to get a value but how can it work in HLE or simulate in HLE (for the graphic plugin?)

Thanks for advice!

**Comment by PeterLemon** [comment]
Hi olivieryuyu,

Hmm I do not know, I have never tried making a test for DP clock counts!
