### ISSUE TITLE
DMULTU test needed

### ISSUE THREAD

**Issue by bryanperris** [PeterLemon/N64#11]
Hi Peter, this is a particular test I need tested on the real machine.

Lets say operand RS is 0xFFFFFFFFFFFFFFFF and RS is 2.

Here are results I get from various sources:

Mame: fffffffffffffffffffffffe
GCC unsigned __int128: 01fffffffffffffffe
PJ64: 01fffffffffffffffe

**Comment by fraser125** [comment]
I just did a quick and dirty test running in MAME and hardware. I agree very different results.
MAME
LO: 0xfffffffffffffffffffffffe
HI: 0x00000000ffffffff
Hardware Console:
LO: 0xfffffffffffffffffffffffe
HI: 0x0000000000000001

**Comment by bryanperris** [comment]
Thanks for running this test.  MAME is doing sign extending for DMULTU when it shouldn't but this is half of the issue.  

Now test DMULTU on the console with RS = 0xFFFFFFFFFFFFFFFF and RT = 0xFFFFFFFFFFFFFFFF.

**Comment by fraser125** [comment]
MAME
LO: 0x0000000000000001
HI: 0x0000000100000000
Hardware Console
LO: 0x0000000000000001
HI: 0xFFFFFFFFFFFFFFFE

**Comment by bryanperris** [comment]
Thanks for testing:.

128-bit: 0xFFFFFFFFFFFFFFFE0000000000000001
64-bit:   0xFFFFFFFE00000001
32-bit:   0xFFFE0001
16-bit:   0xFE01
8-bit:     0xE1

It matches the pattern.

**Comment by bryanperris** [comment]
I finally worked out an algorithm for this:

`// Example program
#include <iostream>
#include <string>
#include <iomanip>

using namespace std;

typedef unsigned long long inttype;
const int shift = 32;
const unsigned int mask = 0xFFFFFFFF;

int main()
{
    inttype a = 0xFFFFFFFFFFFFFFFF;
    inttype b = 0xFFFFFFFFFFFFFFFF;
    
    inttype A_LO = a & mask;
    inttype A_HI = a >> shift;
    inttype B_LO = b & mask;
    inttype B_HI = b >> shift;
    
    inttype P1 = A_LO * B_LO;
    inttype P2 = A_HI * B_LO;
    inttype P3 = A_LO * B_HI;
    inttype P4 = A_HI * B_HI;
    
    inttype S1 = P1 + (P2 << shift);
    inttype S2 = P2 >> shift;
    inttype S3 = P3 + (P4 << shift);
    inttype S4 = P4 >> shift;
    
    inttype LO = S1 + (S3 << shift);
    inttype HI = S2 + ((S4 + S3) << shift);
    
    std::cout << "0x" << setfill('0') << setw(16) << hex << HI << endl;
    std::cout << "0x" << setfill('0') << setw(16) << hex << LO << endl;
    
    return 0;
}`

**Comment by bryanperris** [comment]
@fraser125  What do you get for the signed version (DMULT) for both tests?  Thanks.

**Comment by fraser125** [comment]
dmult on Console (MAME appears correct)
Input:
RS: 0xFFFFFFFFFFFFFFFF
RT: 0xFFFFFFFFFFFFFFFF
Output
LO: 0x0000000000000001
HI: 0x0000000000000000

Input
RS: 0xFFFFFFFFFFFFFFFF
RT: 0x000000000000002
Output
LO: 0xFFFFFFFFFFFFFFFE
HI: 0xFFFFFFFFFFFFFFFF

**Comment by bryanperris** [comment]
Thanks for running the tests!

**Comment by fraser125** [comment]
Pull Request #12 includes the 2 new tests. Also there is a screenshot and test ROM included.

**Comment by PeterLemon** [comment]
Added fraser125 dmultu test, I will now close this issue, thanks to everybody involved =D
