### ISSUE TITLE
Tests for RSP vector load/store ops?

### ISSUE THREAD

**Issue by birkenfeld** [PeterLemon/N64#2]
I'm using the test ROMs from this project for my hobby emulator, and they have proved very very useful. Especially for the RSP, where documentation is scarce.

One area where I'm quite lost is the different load/store operations of the RSP vector unit (LBV etc.). Source code from different emulators even seems contradictory. Although it would be nice to have ROMs in this repo, I'll also be happy with and grateful for just testcases, or even some more documentation.

**Comment by vgturtle127** [comment]
@birkenfeld Sadly, the RSP is poorly documented. So is the entire RCP, actually.

You should take a look at [cxd4's RSP plugin](https://github.com/cxd4/rsp), though. It is probably the best representation of what the actual RSP does.

**Comment by birkenfeld** [comment]
Hadn't seen that one yet. Will check it out, thanks!

**Comment by MoochMcGee** [comment]
vgturtle127 has no idea what he's talking about, trust me.

**Comment by vgturtle127** [comment]
@MoochMcGee :wink:

**Comment by LegendOfDragoon** [comment]
>Sadly, the RSP is poorly documented. So is the entire RCP, actually.

Uhh, in what way is it poorly documented???

**Comment by vgturtle127** [comment]
@LegendOfDragoon Are you talking about the RSP or the RCP? the RSP is way better documented than the RDP, but there is still next to no low-level documentation of the RCP.

**Comment by LegendOfDragoon** [comment]
8 hours ago, you said the RSP is poorly documented... There's good documentation for both the RSP and RDP...

**Comment by vgturtle127** [comment]
@LegendOfDragoon My understanding was that they were poorly documented, but hey! If you have some resources I would love to see them. :pray:
