### ISSUE TITLE
Horizontal edges get cut off with angrylion's rdp implementation

### ISSUE THREAD

**Issue by Zapeth** [PeterLemon/N64#22]
As the title says, a few pixels are cut off at the left and right side of the screen when rendering with angrylion's rdp implementation, making a character/value output on some of the test roms disappear.

However after digging through his commit messages it seems like his implementation does this on purpose -> https://sourceforge.net/p/angrylions-stuff/code/87/

Can someone confirm if the same happens on real hardware with these test roms? Any one of the tests that renders something at the very edges should suffice, like the rsp/cp2 tests (for example, on RSPCP2VSAR the leftmost and rightmost character is not displayed).

If the issue occurs then the test roms would probably need to be changed accordingly to display as intended, otherwise the assumption stated in the commit message might be incorrect and something else is the problem.

PS: there is also a different issue in angrylion's rdp implementation with the tests that display text, probably related to interlacing, but I have yet to further look into this

**Comment by bryanperris** [comment]
Do you know if the rom is being byteswapped to little endian prior to emulation runtime?  I know that the text in the test roms suffer if they get byteswapped.

**Comment by Zapeth** [comment]
Not sure, but I don't think so, I do know that the pixel cut-off is a direct result of angrylion's linked commit (though I wonder if it is correct).

As for the text display issue, its at least close to readable and after messing around a bit with angrylion's implementation I could verify that it produces the correct even and uneven lines (though only when displayed separately). Once I know more I'll probably open up an issue in the appropriate repository (depending on what my thoughts are on the origin of the problem).

**Comment by cxd4** [comment]
It is very likely correct as-is.  Asking someone to test PeterLemon's ROMs on a real N64 isn't necessarily going to help verify if angrylion's code is right or wrong unless they have special TV capturing equipment.  The overscan effect isn't something you can notice just by looking at the corners of a TV screen; you'd be better off filing the question as an issue with @angrylion7's SourceForge repository and asking him if it happens with the test ROMs.

**Comment by Zapeth** [comment]
It seems someone actually did some screen captures of the test roms, they're not from this repository but heavily based on it and pretty much behave identical to the roms here with the plugin -> https://github.com/mupen64plus/mupen64plus-core/issues/554#issuecomment-383182556

Its somewhat hard to tell if a cut off is happening, but if there is one then its not as large when compared to what the plugin does (for example, the letters at the beginning are cut in half and the zeros at the far right also look less complete than the ones in the captured screens).

I guess it just seems a bit arbitrary to me to cut off the sides by a fixed pixel amount for most cases, thats why I'm a bit skeptical. But you're right, its probably best to take this discussion to his repository, at least once I get around to create an account on sourceforge (I might also mess around a bit with the code first, just to get a better understanding).

**Comment by cxd4** [comment]
There is clearly some minor cutoff in bobby's TV capture images as well; it just isn't as obvious as the emulator view (especially if by angrylion's implementation you mean the CEN64 fork of it, which last I checked just strips out the VI filters).  It can also depend on PAL vs. NTSC among other factors.  It's surprisingly complicated; he'd be able to explain it a lot better than I can.

You can always e-mail him at the gmail address listed on his profile; at least that's what I did since I don't like SourceForge, GoogleCode, or SVN either.
