### ISSUE TITLE
Missing macros?

### ISSUE THREAD

**Issue by ChillyWillyGuru** [PeterLemon/N64#3]
I was looking over some of the demos, like Cycle1TextureTriangle16BPPRGBA16B320X240.asm, and couldn't find a number of macros, like Texture_Triangle or Texture_Coefficients. The gfx include file had some comments on some of the macros, but not the macros themselves.

**Comment by ARM9** [comment]
The rdp instructions aren't macros, they're in the assembler now: https://github.com/ARM9/bass/blob/master/bass/arch/table/n64-rdp.arch

**Comment by PeterLemon** [comment]
Yep I used to use macros to program RDP, but then I made the the N64 RDP arch for bass.

**Comment by ChillyWillyGuru** [comment]
Oh! Wow, I'd have never thought of that. Thanks for pointing me in the right direction. :)
