### ISSUE TITLE
C_EQ_S inaccuracy not caught by test ROM

### ISSUE THREAD

**Issue by loganmc10** [PeterLemon/N64#36]
Just as an FYI, in mupen64plus I came across an inaccuracy in the implementation of CP1 c.eq.s that wasn't picked up by the test ROM, see here:

https://github.com/mupen64plus/mupen64plus-core/pull/731

To be honest, I'm not sure of the exact equation that the emulator got wrong, but doing ```source == target``` produced the wrong result, where ```memcmp(source, target, sizeof(float))``` produced the correct result

**Comment by loganmc10** [comment]
The issue seems to possibly be related to comparing -0.0 to +0.0

In C, doing:
```
float float1 = 0.0f;
float float2= -0.0f;
if (float1 == float2)
```
Will return true, however doing a ```memcmp``` will return false. It would good to know the N64's behaviour when comparing -0.0 and +0.0

**Comment by fraser125** [comment]
The datasheet has this to say regarding all floating point compare operations (i.e. the C.**.* instructions)

> During comparison, the sign of 0 is ignored (+0 = –0). 

`http://datasheets.chipdb.org/NEC/Vr-Series/Vr43xx/U10504EJ7V0UMJ1.pdf` PDF Page 565.
I would expect that memcmp would fail because the sign bit is stored in memory and would make the 2 memory values different.

**Comment by loganmc10** [comment]
Yea I agree something else is probably going wrong, I'm not sure why the memcmp fixed the issue in mupen64plus. It's likely that something else is wrong and this somehow fixed it.

I'll try to do some more investigation, regardless, mupen64plus is doing something wrong that the test ROM is not picking up on

**Comment by Zapeth** [comment]
I did a quick modification of the test rom for testing purposes (changes the first two double/float tests to compare +/- and -/+ 0.0, result is assumed to be that sign doesn't matter, so always true), here's the diff:
```
169,170c169,170
<   PrintString($A0100000,232,32,FontBlack,TEXTDOUBLEB,16) // Print Text String To VRAM Using Font At X,Y Position
<   bc1f CEQDPASSA // Branch On FP False
---
>   PrintString($A0100000,232,32,FontBlack,TEXTDOUBLEB,3) // Print Text String To VRAM Using Font At X,Y Position
>   bc1t CEQDPASSA // Branch On FP True
181c181
<   la a0,VALUEDOUBLEC // A0 = Double Data Offset
---
>   la a0,VALUEDOUBLEA // A0 = Double Data Offset
186c186
<   PrintString($A0100000,232,48,FontBlack,TEXTDOUBLEB,16) // Print Text String To VRAM Using Font At X,Y Position
---
>   PrintString($A0100000,232,48,FontBlack,TEXTDOUBLEB,3) // Print Text String To VRAM Using Font At X,Y Position
188,190c188,190
<   PrintValue($A0100000,88,56,FontBlack,VALUEDOUBLEC,7) // Print HEX Chars To VRAM Using Font At X,Y Position
<   PrintString($A0100000,288,56,FontBlack,TEXTDOUBLEC,9) // Print Text String To VRAM Using Font At X,Y Position
<   bc1f CEQDPASSB // Branch On FP False
---
>   PrintValue($A0100000,88,56,FontBlack,VALUEDOUBLEA,7) // Print HEX Chars To VRAM Using Font At X,Y Position
>   PrintString($A0100000,288,56,FontBlack,TEXTDOUBLEA,2) // Print Text String To VRAM Using Font At X,Y Position
>   bc1t CEQDPASSB // Branch On FP True
351,352c351,352
<   PrintString($A0100000,296,248,FontBlack,TEXTFLOATB,8) // Print Text String To VRAM Using Font At X,Y Position
<   bc1f CEQSPASSA // Branch On FP False
---
>   PrintString($A0100000,296,248,FontBlack,TEXTFLOATB,3) // Print Text String To VRAM Using Font At X,Y Position
>   bc1t CEQSPASSA // Branch On FP True
363c363
<   la a0,VALUEFLOATC // A0 = Float Data Offset
---
>   la a0,VALUEFLOATA // A0 = Float Data Offset
368c368
<   PrintString($A0100000,296,264,FontBlack,TEXTFLOATB,8) // Print Text String To VRAM Using Font At X,Y Position
---
>   PrintString($A0100000,296,264,FontBlack,TEXTFLOATB,3) // Print Text String To VRAM Using Font At X,Y Position
370,372c370,372
<   PrintValue($A0100000,152,272,FontBlack,VALUEFLOATC,3) // Print HEX Chars To VRAM Using Font At X,Y Position
<   PrintString($A0100000,320,272,FontBlack,TEXTFLOATC,5) // Print Text String To VRAM Using Font At X,Y Position
<   bc1f CEQSPASSB // Branch On FP False
---
>   PrintValue($A0100000,152,272,FontBlack,VALUEFLOATA,3) // Print HEX Chars To VRAM Using Font At X,Y Position
>   PrintString($A0100000,320,272,FontBlack,TEXTFLOATA,2) // Print Text String To VRAM Using Font At X,Y Position
>   bc1t CEQSPASSB // Branch On FP True
563c563
<   db "12345678.67891234"
---
>   db "-0.0"
578c578
<   db "1234.6789"
---
>   db "-0.0"
597c597
<   float64 12345678.67891234
---
>   float64 -0.0
612c612
<   float32 1234.6789
---
>   float32 -0.0
```

**Comment by loganmc10** [comment]
Some good investigation into the issue here:

https://github.com/mupen64plus/mupen64plus-core/pull/731#issuecomment-596057690

It would be good to update the test ROM to catch this case

**Comment by Zapeth** [comment]
In the process of debugging this issue I ended up replacing pretty much all the all the test values, effectively ending up with a second test set.

Now it also tests for NaN, Inf and denormalized values (though I have yet to come up with some denormalized double values). In addition to that I added the FCR31 register to the printed values in order to provide more information (might be interesting for the Cause bits), though I'm not sure if it needs to be manually cleaned after each test.

However before I submit it I'd like someone to test it on hardware in case some test results are not as expected. Just reply here and I'll post the rom file, a picture of the results should suffice.

**Comment by loganmc10** [comment]
I actually just bought an N64 and I have an everdrive on the way, I can try when it gets here.

It would probably be good too to test with the FS bit set and unset, to make sure the emulator is honoring that setting

**Comment by Zapeth** [comment]
Thats good to hear, maybe you could also check the TLUT InternalPalette test rom if you have the time? (see https://github.com/PeterLemon/N64/issues/30, I just need a rough visual comparison, so a screenshot should suffice).

[Test rom is attached](https://github.com/PeterLemon/N64/files/4309135/CP1CEQ.zip), there are no extra bits set for the FCR31 register right now (though I don't think FS bit would make a difference for comparison operations anyway).

Suffice to say that there are a _lot_ of scenarios still not covered by the existing test roms, and thats just the FPU (and not just the FS bit and/or exceptions but also the different rounding modes and the specifics of the FR bit in cp0 status register).

It depends how much time one is willing to "waste", but I feel like this project needs a major overhaul in terms of shared code and required effort to create/modify tests.
Don't get me wrong, I'm still grateful for the existing tests but they only get you so far if you want to explore every last detail.

**Comment by sp1187** [comment]
I get all tests in the test ROM passed in real hardware.

**Comment by Zapeth** [comment]
Thats good to know, thanks for the quick reply. Do the values of FCR31 display anything other than 0 and the occasional 0x800000?

@PeterLemon would it suffice for you if I submit a PR with just the asm file or do you want the compiled rom and a screenshot as well? Also I would add it as a second test/folder (EQ2 or something like that) since I don't think the original test file would become obsolete with these other values.

**Comment by loganmc10** [comment]
@Zapeth I'm a little confused by this. right now the PR I have pending looks like this:
![image](https://user-images.githubusercontent.com/848146/76355993-d38f5500-62da-11ea-89cd-484a7b964e37.png)

If I force DAZ mode to off, it looks like this:
![image](https://user-images.githubusercontent.com/848146/76356108-00dc0300-62db-11ea-8be0-4844b72d96b3.png)
Which looks better, we are still doing something wrong with NaN values, but that is probably a different issue.

My understanding is that DAZ mode should be off when the FS bit is set, since you aren't setting the FS bit in the test ROM, why is it behaving this way?

**Comment by Zapeth** [comment]
What is your system setup/configuration like? I'm a bit surprised that the NaN tests fail for you, they never failed for me in mupen64 (independent of DAZ/FTZ setting) and CEN64.

Have you managed to test it on real hardware yet? I'd still like to see a screenshot/picture of that, if only for the output of FCR31 of each test.

As for the FS bit test, [this rom](https://github.com/PeterLemon/N64/files/4329619/CP1CEQ_fs.zip) should set it before executing the tests, so feel free to test it on real hardware as well if you want to be sure.

**Comment by loganmc10** [comment]
> What is your system setup/configuration like? I'm a bit surprised that the NaN tests fail for you, they never failed for me in mupen64 (independent of DAZ/FTZ setting) and CEN64.

I'm testing on Linux using GCC. I realized the problem with NaN, the Makefile had -ffast-math set, which makes the NaN comparisons fail, I updated my PR over at mupen64plus-core to remove that.

I'm still waiting for my Everdrive, hopefully soon, I ordered it about 2 weeks ago, I guess it's coming from the Ukraine so it may take a bit.

**Comment by Zapeth** [comment]
Weird, there's no difference for me with -ffast-math (even if set explicitly outside the Makefile and with -O3), might be platform differences? (using gcc-mingw64 here)

**Comment by loganmc10** [comment]
When you say no difference, you mean NaN fails either way? Or it passes either way?

For me, NaN fails using the recompiler either way, but it passes using the cached interpreter and -ffast-math removed

**Comment by Zapeth** [comment]
It passes either way (never got it to fail in fact). I'm strictly testing with Pure Interpreter btw, probably won't spend time with other modes on mupen64.

Though thats implementation specific stuff, so this might be going offtopic here (maybe better to continue this at https://github.com/mupen64plus/mupen64plus-core/pull/731?).
