### ISSUE TITLE
How to calculate framebuffer height from VI registers?

### ISSUE THREAD

**Issue by olivieryuyu** [PeterLemon/N64#4]
Hello,

First of all, thanks for your work on the N64, a great pleasure to see that someone is so in the N64 still nowadays.

I have a question on the calculation of the framebuffer height from the VI registers.

I can see that the width of the framebuffer is provided by VI_WIDTH_REG but is there a way to calculate its height? There is no register for it as such :(

Thanks a lot for your lights

**Comment by PeterLemon** [comment]
Hi olivieryuyu,

If you look at my framebuffer calculation macro here, you will see how I calculate the VI height:
https://github.com/PeterLemon/N64/blob/master/LIB/N64_GFX.INC#L64-L67

I have only tested 320x240 & 640x480 resolutions with this macro, but it seems to work well...

I used the document here to help me learn what figures to use (Page 6 & 7):
https://dragonminded.com/n64dev/Reality%20Coprocessor.pdf

Hope this helps, I will close this issue now.

**Comment by cxd4** [comment]
It is only possible to calculate the height of the actively read portion of the frame buffer.

Calculating the entire _written_ (not only the read) raster frame buffer lines is not possible.  That is data managed by the game's native CPU code in the C language they wrote--outside the jurisdiction of the VI registers' access.

Most games write more frame buffer lines than the N64 VI will read.  (The most common example is the 320x240 resolution:  Only 237 of the 240 lines are read by VI DAC.)

**Comment by bryanperris** [comment]
I created a simple webpage for this purpose: https://bryanperris.github.io/n64vi/
Source: https://github.com/bryanperris/n64vi

Just click the button to compute the width and height.

For my emulator, I made the max size of the display buffer to be 640x480.

**Comment by bryanperris** [comment]
Thanks for the feedback.  I agree too, I did not like using the coefficient.  The coeff = 4.0 / 9.0 code there is a leftover from playing with the math but was meant to be removed (or the idea that I tried using it); Some things came from HatCat's notes but also did not make much sense to me. I want the math to be simple.

Maybe eventually, I should dump out the reg configurations from each game, and how far they write actually write in the framebuffer then build profiles out of them.  Then from the tool, you can load these profiles and test out the math.

Other ideas I have is dumping out the RDP display lists, then interpret them in javascript, and then render them using JS implemented software rasterizer into a JS framebuffer. For the texture input, only use dummy texture data.  As for CBF, I want to isolate the code logic and basically create a JS virtual shader to execute against the fS framebuffer.  

Before I start writing the interpreter for entire RCP, I want to break down the RDP into a model, then when working on the RSP core, I want a RDP implementation that only checks the model but doesn't bother rendering anything.

**Comment by bryanperris** [comment]
What would really help with things is sending this website a RCP chip (or the n64 itself): http://visual6502.org/

If they are willing to turn the RCP die into simulation data, we would have a true RCP simulator.
