### ISSUE TITLE
Can you explain how the video player works, and if possible to add my own video.

### ISSUE THREAD

**Issue by briantho** [PeterLemon/N64#45]
Hi, I'm interested in the N64 Video player you created. I'm currently wanting to add a video to convert as a n64 rom. Can you please explain how you did this, as well as the steps required to do this? Thanks.

**Comment by PeterLemon** [comment]
Hi briantho,

Well I have 2 video codecs for N64, one is using "GRB" frames which is like a YUV substitute, where it has full res Green channel (320x240), 1/2 res Red channel (160x120), & 1/4 res Blue channel (80x60), combined together on a static RDP list after decompression.

My other video codec is DCT based, using 8x8 blocks of YUV422 data, which matches the N64 RDP YUV texture format. I use the RSP to decode the DCT blocks fast, then a static RDP list to display the decompressed YUV data. this is not ideal as YUV420 frames compresses much better, e.g 1/2 the data size for the same video & same quality/quantization levels. I hope this helps =D

If you tell me which video codec style you are interested in I can go into more details for you!

**Comment by PeterLemon** [comment]
I should add that my friend Rasky has made a h265 decoder for N64 which compresses way better! he should be releasing the code & you can use ffmpeg to encode one of those videos! https://github.com/rasky

**Comment by briantho** [comment]
Wow, a h265 decoder for the n64 would be just amazing! I don't see any mention of it though. is it something that is going to be released? if so that would be great. 

Anyway, regarding your original response, I guess I'll use the DCT one that's part of your example roms such as big buck bunny. I'm not looking for anything to complicated, just a way to play back a video on a n64 with a everdrive. Also, I know the everdrive can only do a rom of equal or less than 64mb. Which do you think is better? for me, i don't necessarily care, as long as the video plays, it fits within the 64mb limit, and it looks decent. 

Anyway, can you explain the steps for how to convert a video to the required format, as well as creating the rom? I would really appreciate it. Thanks.

**Comment by PeterLemon** [comment]
h265 decoder is planned to be released for all.

Seeing as data is free on a flash cart, you can make anything upto 64MB for your needs. some videos encode really tiny, like if you have your own CGI renders, or 2D cartoon type stuff.

As for my DCT based video decoder, I do not have an easy way to encode a video yet, I use a combination of tools like ffmpeg & my own unreleased tools with .bat files atm lol but I will give you a rundown on how I encode a video:

1. Use ffmpeg to save each frame of a video as 320x240 resolution YUV422 separate files: ffmpeg -i "video.mkv" -r 30 -s 320x240 -pix_fmt yuv422p -f segment -segment_time 0.01 %08d.yuv
2. I then use my own utility to convert each frames data into 8x8 DCT/ZIGZAG/Quantized @ 50% quality compressed block files (%8d.dct) as bytes (64bytes per 8x8 tile): YUV2DCTZIGZAG8BIT 320 240 %8d.yuv %8d.dct 50
3. I then use my own utility to save a byte difference binary file (%8d.d8) for each frame, from their previous frame: videncd8 e 00000001.d8 00000000.dct 00000001.dct ;  upto the last frame, I save the 00000000.dct file as 00000000.d8 as this is the base frame of the video.
4. I then compress all the frames using RLE compression using a GBA/NDS BIOS RLE compression util & rename them to (*.rle): rle -e *.d8
5. I then compress all the .rle files using LZSS compression using a GBA/NDS LZSS compression util & rename them to (*.lz): lzss -ewo *.rle
6. I then pad all the .lz files to be a multiple of 4, using a python script, this helps me decode this LZ77 data straight from ROM
7. Finally I concatenate the *.lz files into 1 single "Video.lz" file: copy /b *.lz Video.lz

So yep quite a lot of steps, I really need to make a nice util that does this all in 1 pass ideally.

I have several reasons why you should not use my dct video in it's current state:
1. Hard to encode videos atm
2. YUV frames are using the N64 native YUV422 texture format, this is not ideal as if I use YUV420, the same video files are 1/2 the size! So I am in the process of updating my DCT video player atm to be able to decode this smaller video file.
3. my DCT video decoder seems to have a bug atm where it runs on 64drive & everdrive flash carts from the menu, but when I cold boot it on 64drive USB mode, it crashes, so it is not stable software atm!

Anyway I hope that helps you understand the stage I'm at with my video codec stuff, & if you decide todo it yourself you can get a good idea of how it works!

**Comment by briantho** [comment]
Hmm, ok. Thats quite a bit of work to convert to the DCT format, plus your also saying it doesn't work from a "cold boot" on a flash cart. what about the other codec? is it any easier/less steps? do you have any example roms of the GRB format? i was just wondering. If the other codec is simpler to do and more stable, i would be happy to use that. Just let me know if the GRB codec is less complicated, otherwise, i could wait till either the h.265 decoder is ready,  or if you make it somewhat easier to use the DCT codec. Thanks again for the explanation.

**Comment by PeterLemon** [comment]
GRB is similar steps, but simpler to decode. I have examples of it like my DEVO music video: https://github.com/PeterLemon/N64/tree/master/Video/Devo-TimeOutForFun

it is more stable & works from cold boot. but yep when I make an ultimate video codec I'll def makes tools that are easy to use!

**Comment by briantho** [comment]
Ok, thanks. Please let me know when you create an easier way to do this. I'm very interested in one day testing this out with my own videos. For now I'm going to close this issue. Please let me know when your tool is ready, as i am eager to test it. Thanks again
