### ISSUE TITLE
Graphic Artifacts on SetScreenNTSC and SetScreenPAL

### ISSUE THREAD

**Issue by fraser125** [PeterLemon/N64#6]
When running some of your roms downloaded from the repository (MAME v0.184), I found the following graphical artifacts.
![n64setscreenntsc_graphicartifacts](https://cloud.githubusercontent.com/assets/1725115/25841536/52e48ea4-3455-11e7-853f-66f61545325a.png)
While stepping through the debugger I realized that the value set for the Frame Buffer in the Video Interface was the same memory range I was stepping through. 
`lui t0,$A000     // T0 = Origin (Frame Buffer Origin In Bytes = DRAM)`
`sw t0,4(a0)      // Store Origin To VI Origin Register ($A4400004)`

In my environment changing the first line to 
`lui t0,$A010     // T0 = Origin (Frame Buffer Origin In Bytes = DRAM)`
Gave me a solid black screen. 

The same issue applies to the PAL version as well. 
Thanks again for some great sample code!

**Comment by PeterLemon** [comment]
Hi fraser125,

I intentionally did that to show something on screen after the my 1st init code, but I can see why you moved the origin to a clean space of VRAM, thanks for your findings & keep up the good work.
I will be checking your tutorial from time to time =D

**Comment by fraser125** [comment]
That makes sense, I was probably happier to see that then I was to see a pure black screen. 😉 It was also kind of cool to realize that the colors were actually "based on the code".
