### ISSUE TITLE
3D demo?

### ISSUE THREAD

**Issue by Dwood15** [PeterLemon/N64#9]
Just wanted to ask if you could include your own 3D demos like the ones from https://reddit.com/r/n64homebrew's C examples.

**Comment by fraser125** [comment]
How about 6 spinning 3D Cubes?
[https://github.com/PeterLemon/N64/tree/master/RDP/16BPP/Triangle/Cube/FillTriangle320x240](https://github.com/PeterLemon/N64/tree/master/RDP/16BPP/Triangle/Cube/FillTriangle320x240)

**Comment by PeterLemon** [comment]
Hi Dwood15,

Yep I will be adding more 3D examples, I am making a 3D lib using the RSP atm, & will be adding more 3D demos.

The cube demo Fraser125 mentioned above was a WIP FPU 3D lib using the COP1 of the the MIPS CPU, testing 3D transformations, objects & scene processing, with polygon culling (front & back).

The 2 rows represent Left & Right Major triangle calculations, with unsorted faces / back face culling / front face culling.
